[custom]
;不要随意改变关键字，否则会导致出错

;规则集定义
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo-lite/geosite/cn.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo-lite/geoip/cn.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ColinWangLong/ACL4SSR-CM/refs/heads/main/Direct.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL

;策略组定义
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🇯🇵 日本节点`[]☑️ VIP`[]🐸 手动切换
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`600,,10
custom_proxy_group=🐸 手动切换`select`.*
custom_proxy_group=🇯🇵 日本节点`url-test`(日本)`http://www.gstatic.com/generate_204`600,,10
custom_proxy_group=☑️ VIP`url-test`(JP|SG|KR|US|GB|DE|NL|HK)`http://www.gstatic.com/generate_204`600,,10
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT


enable_rule_generator=true
overwrite_original_rules=true
